version: 2.1

jobs:
  build:

    # Primary container image where all commands run
    docker:
      - image: cimg/node
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test

    # Service container image
      - image: cimg/postgres
        environment:
          POSTGRES_USER: postgres

    steps:
      - checkout
      - run: npm i 
