version: 2.1

jobs:
  build:

    # Primary container image where all commands run
    docker:
      - image: circleci/node
        environment:
          DATABASE_URL: postgresql://postgres@localhost/circle_test


    # Service container image
      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres


    steps:
      - checkout
      - run: npm i 
      - run : npm test
