version: 2.1

jobs:
  build:

    # Primary container image where all commands run
    docker:
      - image: circleci/node
        environment:
          DATABASE_URL: postgresql://postgres@localhost/circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference


    # Service container image
      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference


    steps:
      - checkout
      - run: npm i 
      - run : npm test
